name: test_fltter_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  flutter_hooks:
  flutter_riverpod: ^2.3.6
  firebase_auth: ^4.6.3
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


