// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4HS9zGU-4ukYvsHpN0z2A0zOGnQe8TYk',
    appId: '1:614431980669:web:3c1ccde4fc60d65ac48514',
    messagingSenderId: '614431980669',
    projectId: 'daichitest-88737',
    authDomain: 'daichitest-88737.firebaseapp.com',
    storageBucket: 'daichitest-88737.appspot.com',
    measurementId: 'G-KXNJGWCF4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP4vDw9Yjv-LU_kT11fOI0mp2r0NYBxaI',
    appId: '1:614431980669:android:650e6fe553cbd4d8c48514',
    messagingSenderId: '614431980669',
    projectId: 'daichitest-88737',
    storageBucket: 'daichitest-88737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUq-jcDPsz0YlFPn2S3oexzwYF2v-FHMc',
    appId: '1:614431980669:ios:cd3ce1f4714c6007c48514',
    messagingSenderId: '614431980669',
    projectId: 'daichitest-88737',
    storageBucket: 'daichitest-88737.appspot.com',
    iosClientId: '614431980669-9pm2nshvc2l0nbdr4e2svtla397ennp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFltterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUq-jcDPsz0YlFPn2S3oexzwYF2v-FHMc',
    appId: '1:614431980669:ios:54d7536b4667de00c48514',
    messagingSenderId: '614431980669',
    projectId: 'daichitest-88737',
    storageBucket: 'daichitest-88737.appspot.com',
    iosClientId: '614431980669-5fv98h7pmle9f6fd5ev6rkaq00me4fkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFltterApp.RunnerTests',
  );
}
