// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAI0b-fAXm1mxKkcs1kemnB7kCQLgpvI',
    appId: '1:438511184427:web:c8dc4ef40859d2104a586e',
    messagingSenderId: '438511184427',
    projectId: 'our-story-test-f302e',
    authDomain: 'our-story-test-f302e.firebaseapp.com',
    storageBucket: 'our-story-test-f302e.appspot.com',
    measurementId: 'G-H8P7NKVTLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK59YymeiVQnHcJB6VpVCV7oB9v9cnIL0',
    appId: '1:438511184427:android:58309ff9ccb3695e4a586e',
    messagingSenderId: '438511184427',
    projectId: 'our-story-test-f302e',
    storageBucket: 'our-story-test-f302e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8_6SxEWBWMwjd8h4p36uWkLWg1fK_Z0',
    appId: '1:438511184427:ios:48589e68064fdbe84a586e',
    messagingSenderId: '438511184427',
    projectId: 'our-story-test-f302e',
    storageBucket: 'our-story-test-f302e.appspot.com',
    iosClientId: '438511184427-pkni9nq230greu3sg4085la9jcrjh4r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8_6SxEWBWMwjd8h4p36uWkLWg1fK_Z0',
    appId: '1:438511184427:ios:fff08ba6adb962204a586e',
    messagingSenderId: '438511184427',
    projectId: 'our-story-test-f302e',
    storageBucket: 'our-story-test-f302e.appspot.com',
    iosClientId: '438511184427-1tl99ikkp70spj4oinic2k1dacn3n4o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourStory.RunnerTests',
  );
}
